spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  h2.console.path: /h2-console
##
##
security:
  oauth2:
    resource:
      filter-order: 3

credit-point-api:
  ribbon:
    listOfServers: https://www.random.org/integers/?num=1&min=0&max=1500&col=1&base=10&format=plain
